title:            datamap
description:      Navigate through the Data Science resources at UC Berkeley.
url:              "http://localhost:4000" #http://marwahaha.github.io/datamap" # Site url, without a slash at the end.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.
encoding: utf-8

links:
  - name:         datamap
    url:          /
  - name:         Courses
    url:          /courses
  - name:         Projects
    url:          /projects
  - name:         Support
    url:          /support
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart
